#ifndef _SLAKE_BASEDEFS_H_
#define _SLAKE_BASEDEFS_H_

#include <peff/base/basedefs.h>

#if SLAKE_BUILD_SHARED
	#if SLAKE_IS_BUILDING
		#define SLAKE_API PEFF_DLLEXPORT
	#else
		#define SLAKE_API PEFF_DLLIMPORT
	#endif
#else
	#define SLAKE_API
#endif

#define SLAKE_FORCEINLINE PEFF_FORCEINLINE

#define SLAKE_REFERENCED_PARAM(n) ((void)n)
#define SLAKE_REFERENCED_VAR(n) ((void)n)

#define SLAKE_REQUIRES_CONCEPT(...) PEFF_REQUIRES_CONCEPT(__VA_ARGS__)

#define SLAKE_UNREACHABLE() PEFF_UNREACHABLE()

#define SLAKE_RESTRICT PEFF_RESTRICT

#endif
