#ifndef _SLAKE_OPCODE_H_
#define _SLAKE_OPCODE_H_

#include <cstdint>
#include "basedefs.h"

#define SLAKE_OPCODE_ENTRIES      \
	SLAKE_OPCODE_ENTRY(LVALUE)    \
	SLAKE_OPCODE_ENTRY(STORE)     \
                                  \
	SLAKE_OPCODE_ENTRY(JMP)       \
	SLAKE_OPCODE_ENTRY(BR)        \
                                  \
	SLAKE_OPCODE_ENTRY(PHI)       \
                                  \
	SLAKE_OPCODE_ENTRY(LARGV)     \
                                  \
	SLAKE_OPCODE_ENTRY(ADDI8)     \
	SLAKE_OPCODE_ENTRY(ADDI16)    \
	SLAKE_OPCODE_ENTRY(ADDI32)    \
	SLAKE_OPCODE_ENTRY(ADDI64)    \
	SLAKE_OPCODE_ENTRY(ADDISIZE)  \
	SLAKE_OPCODE_ENTRY(ADDU8)     \
	SLAKE_OPCODE_ENTRY(ADDU16)    \
	SLAKE_OPCODE_ENTRY(ADDU32)    \
	SLAKE_OPCODE_ENTRY(ADDU64)    \
	SLAKE_OPCODE_ENTRY(ADDUSIZE)  \
	SLAKE_OPCODE_ENTRY(ADDF32)    \
	SLAKE_OPCODE_ENTRY(ADDF64)    \
                                  \
	SLAKE_OPCODE_ENTRY(SUBI8)     \
	SLAKE_OPCODE_ENTRY(SUBI16)    \
	SLAKE_OPCODE_ENTRY(SUBI32)    \
	SLAKE_OPCODE_ENTRY(SUBI64)    \
	SLAKE_OPCODE_ENTRY(SUBISIZE)  \
	SLAKE_OPCODE_ENTRY(SUBU8)     \
	SLAKE_OPCODE_ENTRY(SUBU16)    \
	SLAKE_OPCODE_ENTRY(SUBU32)    \
	SLAKE_OPCODE_ENTRY(SUBU64)    \
	SLAKE_OPCODE_ENTRY(SUBUSIZE)  \
	SLAKE_OPCODE_ENTRY(SUBF32)    \
	SLAKE_OPCODE_ENTRY(SUBF64)    \
                                  \
	SLAKE_OPCODE_ENTRY(MULI8)     \
	SLAKE_OPCODE_ENTRY(MULI16)    \
	SLAKE_OPCODE_ENTRY(MULI32)    \
	SLAKE_OPCODE_ENTRY(MULI64)    \
	SLAKE_OPCODE_ENTRY(MULISIZE)  \
	SLAKE_OPCODE_ENTRY(MULU8)     \
	SLAKE_OPCODE_ENTRY(MULU16)    \
	SLAKE_OPCODE_ENTRY(MULU32)    \
	SLAKE_OPCODE_ENTRY(MULU64)    \
	SLAKE_OPCODE_ENTRY(MULUSIZE)  \
	SLAKE_OPCODE_ENTRY(MULF32)    \
	SLAKE_OPCODE_ENTRY(MULF64)    \
                                  \
	SLAKE_OPCODE_ENTRY(DIVI8)     \
	SLAKE_OPCODE_ENTRY(DIVI16)    \
	SLAKE_OPCODE_ENTRY(DIVI32)    \
	SLAKE_OPCODE_ENTRY(DIVI64)    \
	SLAKE_OPCODE_ENTRY(DIVISIZE)  \
	SLAKE_OPCODE_ENTRY(DIVU8)     \
	SLAKE_OPCODE_ENTRY(DIVU16)    \
	SLAKE_OPCODE_ENTRY(DIVU32)    \
	SLAKE_OPCODE_ENTRY(DIVU64)    \
	SLAKE_OPCODE_ENTRY(DIVUSIZE)  \
	SLAKE_OPCODE_ENTRY(DIVF32)    \
	SLAKE_OPCODE_ENTRY(DIVF64)    \
                                  \
	SLAKE_OPCODE_ENTRY(MODI8)     \
	SLAKE_OPCODE_ENTRY(MODI16)    \
	SLAKE_OPCODE_ENTRY(MODI32)    \
	SLAKE_OPCODE_ENTRY(MODI64)    \
	SLAKE_OPCODE_ENTRY(MODISIZE)  \
	SLAKE_OPCODE_ENTRY(MODU8)     \
	SLAKE_OPCODE_ENTRY(MODU16)    \
	SLAKE_OPCODE_ENTRY(MODU32)    \
	SLAKE_OPCODE_ENTRY(MODU64)    \
	SLAKE_OPCODE_ENTRY(MODUSIZE)  \
	SLAKE_OPCODE_ENTRY(MODF32)    \
	SLAKE_OPCODE_ENTRY(MODF64)    \
                                  \
	SLAKE_OPCODE_ENTRY(ANDI8)     \
	SLAKE_OPCODE_ENTRY(ANDI16)    \
	SLAKE_OPCODE_ENTRY(ANDI32)    \
	SLAKE_OPCODE_ENTRY(ANDI64)    \
	SLAKE_OPCODE_ENTRY(ANDISIZE)  \
	SLAKE_OPCODE_ENTRY(ANDU8)     \
	SLAKE_OPCODE_ENTRY(ANDU16)    \
	SLAKE_OPCODE_ENTRY(ANDU32)    \
	SLAKE_OPCODE_ENTRY(ANDU64)    \
	SLAKE_OPCODE_ENTRY(ANDUSIZE)  \
	SLAKE_OPCODE_ENTRY(ANDBOOL)   \
                                  \
	SLAKE_OPCODE_ENTRY(ORI8)      \
	SLAKE_OPCODE_ENTRY(ORI16)     \
	SLAKE_OPCODE_ENTRY(ORI32)     \
	SLAKE_OPCODE_ENTRY(ORI64)     \
	SLAKE_OPCODE_ENTRY(ORISIZE)   \
	SLAKE_OPCODE_ENTRY(ORU8)      \
	SLAKE_OPCODE_ENTRY(ORU16)     \
	SLAKE_OPCODE_ENTRY(ORU32)     \
	SLAKE_OPCODE_ENTRY(ORU64)     \
	SLAKE_OPCODE_ENTRY(ORUSIZE)   \
	SLAKE_OPCODE_ENTRY(ORBOOL)    \
                                  \
	SLAKE_OPCODE_ENTRY(XORI8)     \
	SLAKE_OPCODE_ENTRY(XORI16)    \
	SLAKE_OPCODE_ENTRY(XORI32)    \
	SLAKE_OPCODE_ENTRY(XORI64)    \
	SLAKE_OPCODE_ENTRY(XORISIZE)  \
	SLAKE_OPCODE_ENTRY(XORU8)     \
	SLAKE_OPCODE_ENTRY(XORU16)    \
	SLAKE_OPCODE_ENTRY(XORU32)    \
	SLAKE_OPCODE_ENTRY(XORU64)    \
	SLAKE_OPCODE_ENTRY(XORUSIZE)  \
                                  \
	SLAKE_OPCODE_ENTRY(EQI8)      \
	SLAKE_OPCODE_ENTRY(EQI16)     \
	SLAKE_OPCODE_ENTRY(EQI32)     \
	SLAKE_OPCODE_ENTRY(EQI64)     \
	SLAKE_OPCODE_ENTRY(EQISIZE)   \
	SLAKE_OPCODE_ENTRY(EQU8)      \
	SLAKE_OPCODE_ENTRY(EQU16)     \
	SLAKE_OPCODE_ENTRY(EQU32)     \
	SLAKE_OPCODE_ENTRY(EQU64)     \
	SLAKE_OPCODE_ENTRY(EQUSIZE)   \
	SLAKE_OPCODE_ENTRY(EQF32)     \
	SLAKE_OPCODE_ENTRY(EQF64)     \
	SLAKE_OPCODE_ENTRY(EQBOOL)    \
	SLAKE_OPCODE_ENTRY(EQREF)     \
	SLAKE_OPCODE_ENTRY(EQTYPE)    \
                                  \
	SLAKE_OPCODE_ENTRY(NEQI8)     \
	SLAKE_OPCODE_ENTRY(NEQI16)    \
	SLAKE_OPCODE_ENTRY(NEQI32)    \
	SLAKE_OPCODE_ENTRY(NEQI64)    \
	SLAKE_OPCODE_ENTRY(NEQISIZE)  \
	SLAKE_OPCODE_ENTRY(NEQU8)     \
	SLAKE_OPCODE_ENTRY(NEQU16)    \
	SLAKE_OPCODE_ENTRY(NEQU32)    \
	SLAKE_OPCODE_ENTRY(NEQU64)    \
	SLAKE_OPCODE_ENTRY(NEQUSIZE)  \
	SLAKE_OPCODE_ENTRY(NEQF32)    \
	SLAKE_OPCODE_ENTRY(NEQF64)    \
	SLAKE_OPCODE_ENTRY(NEQBOOL)   \
	SLAKE_OPCODE_ENTRY(NEQSTR)    \
	SLAKE_OPCODE_ENTRY(NEQREF)    \
	SLAKE_OPCODE_ENTRY(NEQTYPE)   \
                                  \
	SLAKE_OPCODE_ENTRY(LTI8)      \
	SLAKE_OPCODE_ENTRY(LTI16)     \
	SLAKE_OPCODE_ENTRY(LTI32)     \
	SLAKE_OPCODE_ENTRY(LTI64)     \
	SLAKE_OPCODE_ENTRY(LTISIZE)   \
	SLAKE_OPCODE_ENTRY(LTU8)      \
	SLAKE_OPCODE_ENTRY(LTU16)     \
	SLAKE_OPCODE_ENTRY(LTU32)     \
	SLAKE_OPCODE_ENTRY(LTU64)     \
	SLAKE_OPCODE_ENTRY(LTUSIZE)   \
	SLAKE_OPCODE_ENTRY(LTF32)     \
	SLAKE_OPCODE_ENTRY(LTF64)     \
                                  \
	SLAKE_OPCODE_ENTRY(GTI8)      \
	SLAKE_OPCODE_ENTRY(GTI16)     \
	SLAKE_OPCODE_ENTRY(GTI32)     \
	SLAKE_OPCODE_ENTRY(GTI64)     \
	SLAKE_OPCODE_ENTRY(GTISIZE)   \
	SLAKE_OPCODE_ENTRY(GTU8)      \
	SLAKE_OPCODE_ENTRY(GTU16)     \
	SLAKE_OPCODE_ENTRY(GTU32)     \
	SLAKE_OPCODE_ENTRY(GTU64)     \
	SLAKE_OPCODE_ENTRY(GTUSIZE)   \
	SLAKE_OPCODE_ENTRY(GTF32)     \
	SLAKE_OPCODE_ENTRY(GTF64)     \
                                  \
	SLAKE_OPCODE_ENTRY(LTEQI8)    \
	SLAKE_OPCODE_ENTRY(LTEQI16)   \
	SLAKE_OPCODE_ENTRY(LTEQI32)   \
	SLAKE_OPCODE_ENTRY(LTEQI64)   \
	SLAKE_OPCODE_ENTRY(LTEQISIZE) \
	SLAKE_OPCODE_ENTRY(LTEQU8)    \
	SLAKE_OPCODE_ENTRY(LTEQU16)   \
	SLAKE_OPCODE_ENTRY(LTEQU32)   \
	SLAKE_OPCODE_ENTRY(LTEQU64)   \
	SLAKE_OPCODE_ENTRY(LTEQUSIZE) \
	SLAKE_OPCODE_ENTRY(LTEQF32)   \
	SLAKE_OPCODE_ENTRY(LTEQF64)   \
                                  \
	SLAKE_OPCODE_ENTRY(GTEQI8)    \
	SLAKE_OPCODE_ENTRY(GTEQI16)   \
	SLAKE_OPCODE_ENTRY(GTEQI32)   \
	SLAKE_OPCODE_ENTRY(GTEQI64)   \
	SLAKE_OPCODE_ENTRY(GTEQISIZE) \
	SLAKE_OPCODE_ENTRY(GTEQU8)    \
	SLAKE_OPCODE_ENTRY(GTEQU16)   \
	SLAKE_OPCODE_ENTRY(GTEQU32)   \
	SLAKE_OPCODE_ENTRY(GTEQU64)   \
	SLAKE_OPCODE_ENTRY(GTEQUSIZE) \
	SLAKE_OPCODE_ENTRY(GTEQF32)   \
	SLAKE_OPCODE_ENTRY(GTEQF64)   \
                                  \
	SLAKE_OPCODE_ENTRY(SHLI8)     \
	SLAKE_OPCODE_ENTRY(SHLI16)    \
	SLAKE_OPCODE_ENTRY(SHLI32)    \
	SLAKE_OPCODE_ENTRY(SHLI64)    \
	SLAKE_OPCODE_ENTRY(SHLISIZE)  \
	SLAKE_OPCODE_ENTRY(SHLU8)     \
	SLAKE_OPCODE_ENTRY(SHLU16)    \
	SLAKE_OPCODE_ENTRY(SHLU32)    \
	SLAKE_OPCODE_ENTRY(SHLU64)    \
	SLAKE_OPCODE_ENTRY(SHLUSIZE)  \
                                  \
	SLAKE_OPCODE_ENTRY(SHRI8)     \
	SLAKE_OPCODE_ENTRY(SHRI16)    \
	SLAKE_OPCODE_ENTRY(SHRI32)    \
	SLAKE_OPCODE_ENTRY(SHRI64)    \
	SLAKE_OPCODE_ENTRY(SHRISIZE)  \
	SLAKE_OPCODE_ENTRY(SHRU8)     \
	SLAKE_OPCODE_ENTRY(SHRU16)    \
	SLAKE_OPCODE_ENTRY(SHRU32)    \
	SLAKE_OPCODE_ENTRY(SHRU64)    \
	SLAKE_OPCODE_ENTRY(SHRUSIZE)  \
                                  \
	SLAKE_OPCODE_ENTRY(CMPI8)     \
	SLAKE_OPCODE_ENTRY(CMPI16)    \
	SLAKE_OPCODE_ENTRY(CMPI32)    \
	SLAKE_OPCODE_ENTRY(CMPI64)    \
	SLAKE_OPCODE_ENTRY(CMPISIZE)  \
	SLAKE_OPCODE_ENTRY(CMPU8)     \
	SLAKE_OPCODE_ENTRY(CMPU16)    \
	SLAKE_OPCODE_ENTRY(CMPU32)    \
	SLAKE_OPCODE_ENTRY(CMPU64)    \
	SLAKE_OPCODE_ENTRY(CMPUSIZE)  \
	SLAKE_OPCODE_ENTRY(CMPF32)    \
	SLAKE_OPCODE_ENTRY(CMPF64)    \
                                  \
	SLAKE_OPCODE_ENTRY(NOT)       \
	SLAKE_OPCODE_ENTRY(NEG)       \
                                  \
	SLAKE_OPCODE_ENTRY(AT)        \
                                  \
	SLAKE_OPCODE_ENTRY(LOAD)      \
	SLAKE_OPCODE_ENTRY(RLOAD)     \
                                  \
	SLAKE_OPCODE_ENTRY(LCURFN)    \
                                  \
	SLAKE_OPCODE_ENTRY(COPYI8)    \
	SLAKE_OPCODE_ENTRY(COPYI16)   \
	SLAKE_OPCODE_ENTRY(COPYI32)   \
	SLAKE_OPCODE_ENTRY(COPYI64)   \
	SLAKE_OPCODE_ENTRY(COPYISIZE) \
	SLAKE_OPCODE_ENTRY(COPYU8)    \
	SLAKE_OPCODE_ENTRY(COPYU16)   \
	SLAKE_OPCODE_ENTRY(COPYU32)   \
	SLAKE_OPCODE_ENTRY(COPYU64)   \
	SLAKE_OPCODE_ENTRY(COPYUSIZE) \
	SLAKE_OPCODE_ENTRY(COPYF32)   \
	SLAKE_OPCODE_ENTRY(COPYF64)   \
	SLAKE_OPCODE_ENTRY(COPYBOOL)  \
	SLAKE_OPCODE_ENTRY(COPYNULL)  \
                                  \
	SLAKE_OPCODE_ENTRY(COPY)      \
                                  \
	SLAKE_OPCODE_ENTRY(LARG)      \
	SLAKE_OPCODE_ENTRY(LAPARG)    \
                                  \
	SLAKE_OPCODE_ENTRY(LVAR)      \
	SLAKE_OPCODE_ENTRY(ALLOCA)    \
                                  \
	SLAKE_OPCODE_ENTRY(ENTER)     \
	SLAKE_OPCODE_ENTRY(LEAVE)     \
                                  \
	SLAKE_OPCODE_ENTRY(PUSHARG)   \
	SLAKE_OPCODE_ENTRY(PUSHAP)    \
                                  \
	SLAKE_OPCODE_ENTRY(CALL)      \
	SLAKE_OPCODE_ENTRY(MCALL)     \
	SLAKE_OPCODE_ENTRY(CTORCALL)  \
	SLAKE_OPCODE_ENTRY(RETVOID)   \
	SLAKE_OPCODE_ENTRY(RET)       \
                                  \
	SLAKE_OPCODE_ENTRY(COCALL)    \
	SLAKE_OPCODE_ENTRY(COMCALL)   \
	SLAKE_OPCODE_ENTRY(CORETVOID) \
	SLAKE_OPCODE_ENTRY(CORET)     \
	SLAKE_OPCODE_ENTRY(YIELD)     \
	SLAKE_OPCODE_ENTRY(RESUME)    \
	SLAKE_OPCODE_ENTRY(CODONE)    \
                                  \
	SLAKE_OPCODE_ENTRY(LTHIS)     \
                                  \
	SLAKE_OPCODE_ENTRY(NEW)       \
	SLAKE_OPCODE_ENTRY(ARRNEW)    \
                                  \
	SLAKE_OPCODE_ENTRY(THROW)     \
	SLAKE_OPCODE_ENTRY(PUSHEH)    \
	SLAKE_OPCODE_ENTRY(LEXCEPT)   \
                                  \
	SLAKE_OPCODE_ENTRY(CAST)      \
	SLAKE_OPCODE_ENTRY(NULLCAST)  \
                                  \
	SLAKE_OPCODE_ENTRY(APTOTUPLE) \
                                  \
	SLAKE_OPCODE_ENTRY(DCMT)      \
                                  \
	SLAKE_OPCODE_ENTRY(TYPEOF)    \
                                  \
	SLAKE_OPCODE_ENTRY(CONSTSW)

namespace slake {
#define SLAKE_OPCODE_ENTRY(x) x,
	enum class Opcode : uint16_t {
		INVALID = 0,
		SLAKE_OPCODE_ENTRIES
	};
#undef SLAKE_OPCODE_ENTRY
}

#endif
