#include "opcode.h"

using namespace slake;

#define MNEMONIC_ENTRIES         \
	MNEMONIC_ENTRY(NOP),         \
		MNEMONIC_ENTRY(PUSH),    \
		MNEMONIC_ENTRY(POP),     \
		MNEMONIC_ENTRY(LOAD),    \
		MNEMONIC_ENTRY(RLOAD),   \
		MNEMONIC_ENTRY(STORE),   \
		MNEMONIC_ENTRY(LVAR),    \
		MNEMONIC_ENTRY(REG),     \
		MNEMONIC_ENTRY(LVALUE),  \
		MNEMONIC_ENTRY(ENTER),   \
		MNEMONIC_ENTRY(LEAVE),   \
		MNEMONIC_ENTRY(ADD),     \
		MNEMONIC_ENTRY(SUB),     \
		MNEMONIC_ENTRY(MUL),     \
		MNEMONIC_ENTRY(DIV),     \
		MNEMONIC_ENTRY(MOD),     \
		MNEMONIC_ENTRY(AND),     \
		MNEMONIC_ENTRY(OR),      \
		MNEMONIC_ENTRY(XOR),     \
		MNEMONIC_ENTRY(LAND),    \
		MNEMONIC_ENTRY(LOR),     \
		MNEMONIC_ENTRY(EQ),      \
		MNEMONIC_ENTRY(NEQ),     \
		MNEMONIC_ENTRY(LT),      \
		MNEMONIC_ENTRY(GT),      \
		MNEMONIC_ENTRY(LTEQ),    \
		MNEMONIC_ENTRY(GTEQ),    \
		MNEMONIC_ENTRY(LSH),     \
		MNEMONIC_ENTRY(RSH),     \
		MNEMONIC_ENTRY(REV),     \
		MNEMONIC_ENTRY(NOT),     \
		MNEMONIC_ENTRY(INCF),    \
		MNEMONIC_ENTRY(DECF),    \
		MNEMONIC_ENTRY(INCB),    \
		MNEMONIC_ENTRY(DECB),    \
		MNEMONIC_ENTRY(NEG),     \
		MNEMONIC_ENTRY(AT),      \
		MNEMONIC_ENTRY(JMP),     \
		MNEMONIC_ENTRY(JT),      \
		MNEMONIC_ENTRY(JF),      \
		MNEMONIC_ENTRY(PUSHARG), \
		MNEMONIC_ENTRY(CALL),    \
		MNEMONIC_ENTRY(MCALL),   \
		MNEMONIC_ENTRY(ACALL),   \
		MNEMONIC_ENTRY(AMCALL),  \
		MNEMONIC_ENTRY(YIELD),   \
		MNEMONIC_ENTRY(AWAIT),   \
		MNEMONIC_ENTRY(LTHIS),   \
		MNEMONIC_ENTRY(RET),     \
		MNEMONIC_ENTRY(LRET),    \
		MNEMONIC_ENTRY(NEW),     \
		MNEMONIC_ENTRY(THROW),   \
		MNEMONIC_ENTRY(PUSHXH),  \
		MNEMONIC_ENTRY(LEXCEPT), \
		MNEMONIC_ENTRY(ABORT),   \
		MNEMONIC_ENTRY(CAST),    \
		MNEMONIC_ENTRY(TYPEOF)

#define MNEMONIC_ENTRY(m) \
	{ Opcode::m, #m }

const std::map<Opcode, std::string> slake::OPCODE_MNEMONIC_MAP = {
	MNEMONIC_ENTRIES
};

#undef MNEMONIC_ENTRY

#define MNEMONIC_ENTRY(m) \
	{ #m, Opcode::m }

const std::map<std::string, Opcode> slake::MNEMONIC_OPCODE_MAP = {
	MNEMONIC_ENTRIES
};
